[pytest]
pythonpath = .

testpaths =
    tests
    unit_test

python_files = test_*.py *_test.py check_*.py

addopts =
    -v
    -s
    --maxfail=50
    --tb=short


filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning


