target-version = "py311"
line-length = 120
force-exclude = true

extend-exclude = [
    ".venv",
    "__pycache__",
    ".idea"
]

[lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "C4",
    "UP",
    "SIM",
    "RET",
    "ARG",
    "PL",
    "RUF",
    "E501",
    "B904",
    "PLW0603",
    "UP042",
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "RUF012",
    "RET502",
    "RET504",
    "RET505",
    "PLR5501",
]


[format]
quote-style = "double"
indent-style = "space"